version: "3.7"

services:
  frontend:
    build: queue-manager-client/
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      SERVER_BASE_URL: http://localhost:4000/

  server:
    build: queue-manager-api/
    command: node app.js
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
